# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: jacobcxdev.cq
PackageVersion: 0.33.8
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Commands:
  - cq
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/jacobcxdev/cq/releases/download/v0.33.8/cq_0.33.8_windows_amd64.msi
    InstallerSha256: 4f0be86f4d8feae04770c3a39b6cf939acaf140aee9067f8a53f263411803b97
    AppsAndFeaturesEntries:
      - DisplayName: CQ
        Publisher: jacobcxdev
        DisplayVersion: 0.33.8
        UpgradeCode: '{7B64C2EF-DF57-4C43-8C35-7D1949B09469}'
  - Architecture: arm64
    InstallerUrl: https://github.com/jacobcxdev/cq/releases/download/v0.33.8/cq_0.33.8_windows_arm64.msi
    InstallerSha256: 3994f30bb5cf135d09f33487abe457805073cfc4b3fb4126b2c1a16f80f8082a
    AppsAndFeaturesEntries:
      - DisplayName: CQ
        Publisher: jacobcxdev
        DisplayVersion: 0.33.8
        UpgradeCode: '{7B64C2EF-DF57-4C43-8C35-7D1949B09469}'
ManifestType: installer
ManifestVersion: 1.10.0
